
version: 2

models:
  - name: trusted_tb_discounts
    description: "Max values allowed for discounts"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: vl_order
        description: "Max order value to allow the discount value"
      - name: vl_discount
        description: "Value in % to be dicounted"

